#!/usr/bin/env python3
"""Level 01 backdrop placeholders: the tile sets and set pieces of Level 01's `backdrop` data.

Outputs (assets/backdrop/level-01/, Git LFS): one PNG per tile set and set piece of
design/campaign/act-1-first-contact/level-01-break-at-dawn/data.yaml, named by its id; frames and
headings as <id>_<n>.png. Sizes come from the data file and are checked.

These are placeholders derived from the *chosen* Earth orbit scene (parallax r03 A): the same
station kit (render/station.py), palette B, Earth texture, cloud-bank shading and haze rules as
parallax_r02.py / parallax_r03.py, cut into the pieces a level needs; only the kit's orange accent
is muted (KIT_PAL), as warm amber is reserved for loot targets. Unlike the other
placeholders they are not copied from a concept sheet, so every PNG carries a "Placeholder" text
chunk naming this script. Scale per layer (perspective rule): far parts are built at full size and
reduced to 0.45; ground at 1:1 (1 world unit = 1 px); low-air at 1:1 but nearer and brighter.
Lighting is the art direction's: point key light top-left, shadows down-right.

Run: python3 tools/concept/backdrop_l01.py [id ...]   (~3 min for everything)
"""
import functools
import sys
from pathlib import Path

import numpy as np
import yaml
from PIL import Image, ImageFilter
from PIL.PngImagePlugin import PngInfo

sys.path.insert(0, str(Path(__file__).resolve().parent))
import parallax_r03 as r03  # noqa: E402
from parallax_r02 import haze, posterize  # noqa: E402
from render import models, raster, sdf, sprite, station, terrain  # noqa: E402
from render.config import ROOT  # noqa: E402
from render.palette import B  # noqa: E402
from render.sdf import mirror_x, rotate_z, sd_box, sd_capsule, sd_cylinder_y, sd_cylinder_z, sd_sphere, union  # noqa: E402
from render.station import ACCENT, DARK, HULL, RED, SOLAR, WARM  # noqa: E402

LEVEL = ROOT / "design" / "campaign" / "act-1-first-contact" / "level-01-break-at-dawn" / "data.yaml"
OUT = ROOT / "assets" / "backdrop" / "level-01"
SEA, LAND = B["EARTH ORBIT"], B["EARTH SURFACE"]
FAR_SCALE = 0.45
# Warm amber on the ground layer is reserved for loot targets (art direction, readability rule 7):
# the station kit's orange UTC accent (palette B ff7a2a) becomes a muted beige ochre, palette B's
# JOVIAN ffb840 mixed 40/60 with ASTEROID BELT 686080. Ships keep palette B's own accents.
MUTED_ACCENT = "a48366"
KIT_PAL = B.variant("UTC ACCENTS", f"0050ff 00a8ff 7ff0ff ff2a6a {MUTED_ACCENT} ffe04a")
NOTE = ("Placeholder for Level 01's backdrop, generated by tools/concept/backdrop_l01.py from the "
        "chosen Earth orbit scene (parallax r03 A); not final art.")


# --------------------------------------------------------------------------- helpers

def blank(w, h):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def part(scene, size, factor=4, colors=40):
    """Render a kit part (station materials, 1 world unit = 1 px) to a native sprite."""
    return station.render_part((scene, size), KIT_PAL, factor=factor, colors=colors)


def put(img, spr, x, y, period=None):
    """Paste centred at (x, y); with a period, also one period above and below (tiling in y)."""
    for yy in (y,) if period is None else (y - period, y, y + period):
        sprite.paste_center(img, spr, x, yy)


def column(img, spr, x, y0, y1):
    """Stack a part (a truss bay) from y0 to y1."""
    for y in range(int(y0), int(y1), spr.height):
        sprite.paste(img, spr, x - spr.width / 2, y)


def with_shadow(low, high, offset=(6, 8)):
    """Tall parts cast a short shadow (6, 8) onto the parts below them (art direction)."""
    sh = blank(*low.size)
    sh.alpha_composite(sprite.shadow_of(high, opacity=0.45, blur=1.2), offset)
    out = low.copy()
    out.alpha_composite(r03.masked(sh, low))
    out.alpha_composite(high)
    return out


def wrap_padded(fn, n, pad=32):
    """Apply an image filter chain to a field that tiles in x and y without seams at the edges."""
    big = np.pad(n, pad, mode="wrap")
    return np.array(fn(big))[pad:-pad, pad:-pad]


def rgba(rgb, alpha):
    return raster.to_rgba_image(rgb, alpha)


def over(dst, src_rgb, src_a):
    """Composite a float rgb/alpha layer over a float RGBA array (alpha 0..1), in place."""
    a = src_a[..., None]
    out_a = a + dst[..., 3:4] * (1 - a)
    dst[..., :3] = (src_rgb * a + dst[..., :3] * dst[..., 3:4] * (1 - a)) / np.maximum(out_a, 1e-6)
    dst[..., 3:4] = out_a


def finish(arr, colors=24, alpha_levels=10):
    """Float RGBA (alpha 0..1) -> posterized image with stepped alpha (90s translucency)."""
    img = rgba(arr[..., :3], arr[..., 3] * 255)
    return r03.step_alpha(posterize(img, colors), alpha_levels)


def stars(w, h, seed, density=0.0012):
    img = raster.starfield(w, h, seed, density=density)
    a = np.array(img).astype(np.float64)
    a[..., :3] *= 0.8                                    # the deep layer recedes
    return a


# --------------------------------------------------------------------------- deep

def earth_tile(w, h):
    """The day side far below, light weather: r02's Earth with fewer, thinner clouds."""
    earth = terrain.earth_coast(w, h, seed=11, period=True, cell=128,
                                stops=terrain.coast_stops_from(SEA, LAND, 0.56))
    e = np.array(earth).astype(np.float64)
    clouds = raster.fbm(w, h, 64, 61, octaves=5, period=True)
    c = np.clip((clouds - 0.6) * 2.4, 0, 0.8)[..., None]
    e[..., :3] = e[..., :3] * (1 - c) + np.array(SEA[5]) * c
    e[..., :3] *= 1 - 0.3 * np.roll(np.roll(c, 4, axis=0), 4, axis=1) * (1 - c)
    grey = e[..., :3].mean(axis=-1, keepdims=True)
    e[..., :3] = (e[..., :3] * 0.6 + grey * 0.4) * 0.5 + np.array(SEA[1]) * 0.5
    return posterize(rgba(e[..., :3], e[..., 3]), 20)


def limb_layer(w, h, inside, depth, seed):
    """Space and the atmosphere rim around Earth's limb, as an overlay on the earth tiles.
    ``inside``: Earth mask; ``depth``: px from the limb (positive inside)."""
    arr = np.zeros((h, w, 4))
    st = stars(w, h, seed)
    arr[~inside, :3] = st[~inside, :3]
    arr[~inside, 3] = 1
    rim = np.array(SEA[4], float)
    glow_out = np.exp(depth / 5.0) * (~inside)           # thin blue atmosphere beyond the limb
    over(arr, rim * 0.8, glow_out * 0.85)
    glow_in = np.exp(-depth / 7.0) * inside               # the limb brightening
    over(arr, rim, glow_in * 0.45)
    return arr


def earth_dawn(w, h):
    """Section 1-2 over the earth tiles: space and the Moon's side bottom-left, Earth's curve,
    the night side with city lights and the sunrise terminator; transparent over the day side.
    Earth covers the whole top edge and the overlay fades out over the top 24 rows, so no edge
    shows when the top scrolls down the screen."""
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    depth = 1510 - np.hypot(xx - 1455, yy - 400)
    inside = depth > 0
    arr = limb_layer(w, h, inside, depth, 9)
    line = yy - (1150 + 0.25 * xx)                          # the terminator, day above it
    night = sdf.smoothstep(-40, 60, line) * inside
    over(arr, np.array(SEA[0], float) + 6, night * 0.72)
    rng = np.random.default_rng(21)
    towns = raster.fbm(w, h, 32, 23, octaves=3, period=False)
    lights = (towns > 0.62) & (rng.random((h, w)) < 0.05) & (night > 0.5)
    over(arr, np.array([210, 180, 120], float), lights * 0.9)
    band = np.exp(-(line / 38.0) ** 2) * inside            # dawn light along the terminator
    over(arr, np.array([200, 150, 100], float), band * 0.28)
    arr[..., 3] *= np.clip(yy / 24, 0, 1)
    return finish(arr)


def earth_limb(w, h, radius=520, below=240, haze_depth=110):
    """Section 5 over the earth tiles: Earth's curve falling behind (a circle whose crest is
    ``below`` px above the bottom edge). Towards the limb the day side hazes into the atmosphere
    colour and darkens over ``haze_depth`` px (the view grazes more air); the atmosphere is a
    thin bright rim, lit a little more towards the key light at the left; beyond it a faint
    airglow fades into open space, whose stars thin out near the rim. Transparent at the bottom
    edge; the opaque top edge stays above the screen until the debrief, after the outro."""
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    crest = h - below
    depth = radius - np.hypot(xx - w * 0.58, yy - crest - radius)   # px inside the limb
    inside = np.clip(depth + 0.5, 0, 1)                              # 1 px anti-aliased edge
    arr = np.zeros((h, w, 4))
    graze = np.clip(1 - depth / haze_depth, 0, 1) ** 2
    over(arr, np.array(SEA[2], float) * (1 - 0.4 * graze)[..., None], 0.85 * graze * inside)
    st = stars(w, h, 13)
    space = st[..., :3] * np.clip(-depth / 60, 0, 1)[..., None]
    over(arr, space, 1 - inside)
    over(arr, np.array(SEA[3], float) * 0.7, 0.3 * np.exp(np.minimum(depth, 0) / 16) * (1 - inside))
    light = 0.8 + 0.2 * (1 - xx / w)
    over(arr, np.array(SEA[4], float), 0.9 * light * np.exp(-((depth + 1) / 2.2) ** 2))
    over(arr, np.array(SEA[5], float), 0.6 * light * np.exp(-((depth + 1) / 1.0) ** 2))
    return finish(arr, colors=32, alpha_levels=24)


def moon(w, h):
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    r = w / 2 - 1
    dx, dy = (xx - w / 2 + 0.5) / r, (yy - h / 2 + 0.5) / r
    d2 = dx * dx + dy * dy
    nz = np.sqrt(np.clip(1 - d2, 0, 1))
    lit = np.clip(-0.55 * dx - 0.6 * dy + 0.6 * nz, 0, 1)    # key light from the top-left
    craters = raster.fbm(w, h, 6, 31, octaves=3, period=False)
    rgb = np.array([150, 155, 170], float) * (0.25 + 0.85 * lit * (0.8 + 0.3 * craters))[..., None]
    img = haze(rgba(rgb, (d2 <= 1) * 255), SEA[2], 0.25)
    return posterize(img, 10)


def vrell_glow(w, h):
    """The strike group's glow on the horizon (top edge), violet into teal, kept dim; the top
    edge stays above the screen until the debrief."""
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    n = raster.fbm(w, h, 40, 41, octaves=4, period=False)
    mix = np.clip(raster.fbm(w, h, 120, 43, octaves=2, period=False) * 1.4 - 0.2, 0, 1)[..., None]
    rgb = np.array([96, 20, 128], float) * (1 - mix) + np.array([0, 140, 100], float) * mix
    a = (1 - yy / h) ** 2.2 * (0.25 + 0.3 * n)
    arr = np.dstack([rgb, a])
    rng = np.random.default_rng(45)
    for _ in range(14):                                     # distant ship lights
        x, y = int(rng.uniform(20, w - 20)), int(rng.uniform(6, 48))
        arr[y, x] = (120, 255, 200, 0.85)
    return finish(arr, 20)


# --------------------------------------------------------------------------- station kit

def rail_bay(bay=38):
    """One bay of a launch rail: a dark bed with two guide strips and a lit marker."""
    def scene(p):
        q = mirror_x(p)
        return union((sd_box(p, (0, 0, 0), (9, bay / 2, 1.5), 0.4), DARK),
                     (sd_box(q, (6, 0, 1.6), (1.2, bay / 2, 0.6), 0.2), HULL),
                     (sd_sphere(p, (0, 0, 1.6), 1.6), WARM))
    return part(scene, (22, bay))


def crane_rail_bay(bay=38, width=84):
    """One bay of a gantry rail bed: two steel rails on a sleeper and a side walkway."""
    hw = width / 2

    def scene(p):
        q = mirror_x(p)
        return union((sd_box(p, (0, 0, -2), (hw - 4, 5, 1.5), 0.5), DARK),
                     (sd_box(q, (hw - 14, 0, 0.5), (2.2, bay / 2, 1.6), 0.4), HULL),
                     (sd_box(q, (hw - 2, 0, -1), (1.6, bay / 2, 1.0), 0.3), ACCENT))
    return part(scene, (width, bay))


KIT = {}


def kit():
    """The round-02 station parts, rendered once."""
    if not KIT:
        KIT.update(
            truss_v=station.render_part(station.truss_v_part(), KIT_PAL),
            drum=station.render_part(station.drum_part(), KIT_PAL),
            drum_s=station.render_part(station.drum_part(16, 30), KIT_PAL),
            solar_l=station.render_part(station.solar_part(140, 56, True), KIT_PAL),
            solar_r=station.render_part(station.solar_part(140, 56, False), KIT_PAL),
            radiator=station.render_part(station.radiator_part(), KIT_PAL),
            dock=station.render_part(station.dock_part(), KIT_PAL),
            dish=station.render_part(station.dish_part(), KIT_PAL),
            turret=station.render_part(station.turret_part(), KIT_PAL),
            cargo=station.render_part(station.cargo_part(), KIT_PAL),
            rail=rail_bay(),
        )
    return KIT


@functools.lru_cache
def truss_h(length, width=26):
    return station.render_part(station.truss_h_part(length, width), KIT_PAL)


# --------------------------------------------------------------------------- far

def north_arm(w, h):
    """The yard's north arm with Aegis Two's launch rail, built at full size and reduced to 0.45."""
    k = kit()
    fw, fh = int(round(w / FAR_SCALE)), int(round(h / FAR_SCALE))
    low, high = blank(fw, fh), blank(fw, fh)
    cx = fw // 2
    for x in (cx - 72, cx + 72):
        column(low, k["truss_v"], x, 0, fh)
    column(low, k["rail"], cx, 90, fh)
    for y in (180, 560, 940, 1300):
        put(low, truss_h(170), cx, y)
    put(low, k["solar_l"], cx - 72, 420)
    put(low, k["solar_r"], cx + 72, 760)
    put(low, k["radiator"], cx + 130, 1120)
    put(high, k["drum"], cx - 72, 1080)
    put(high, k["dish"], cx + 72, 260)
    put(high, k["dock"], cx, 70)
    img = with_shadow(low, high)
    img = img.resize((w, h), Image.BOX)
    img.putalpha(img.getchannel("A").point(lambda v: 255 if v >= 128 else 0))
    return posterize(haze(img, SEA[2], 0.5), 24)


def stormhawk_far(w, h, n):
    """Aegis Two's Stormhawks at the far scale: an angle set, frame i heading i * 360 / n."""
    scene, mats = models.ship_a_model(palette=B.ship_colors())
    frames = []
    for i in range(n):
        angle = -np.radians(i * 360 / n)
        hi = sdf.render(lambda p, a=angle: scene(rotate_z(p, a)), mats, (w * 8, h * 8), 2.0 * w / 22)
        frames.append(posterize(haze(sprite.make_sprite(hi, 8, 16), SEA[2], 0.3), 16))
    return frames


# --------------------------------------------------------------------------- ground

def launch_rail(w, h):
    """The south launch rail (the ship launches up it), between two trusses, ending in a bumper."""
    k = kit()
    low, high = blank(w, h), blank(w, h)
    cx = w // 2
    for x in (cx - 62, cx + 62):
        column(low, k["truss_v"], x, 30, h)
    column(low, k["rail"], cx, 40, h)
    for y in (120, 330, 540):
        put(low, truss_h(150), cx, y)
    put(high, k["drum_s"], cx - 62, 240)
    put(high, k["drum_s"], cx + 62, 470)
    put(high, k["turret"], cx + 62, 640)

    def bumper(p):
        return union((sd_box(p, (0, 0, 0), (16, 5, 4), 1.0), ACCENT), (sd_sphere(p, (0, 0, 4), 2.2), RED))
    put(high, part(bumper, (40, 14)), cx, 34)
    return with_shadow(low, high)


def crossbeam(w, h):
    img = blank(w, h)
    put(img, truss_h(w, 26), w / 2, h / 2)
    return img


def dock_frames_tile(w, h):
    """Open dock frames hanging off a central spine, alternating left and right (period h)."""
    k = kit()
    low, high = blank(w, h), blank(w, h)
    cx = w // 2
    for y in range(0, h, k["truss_v"].height):
        put(low, k["truss_v"], cx, y + k["truss_v"].height / 2, h)
    for side, y0 in ((-1, 30), (1, 330)):
        inner, outer = cx + side * 20, cx + side * 200
        mid = (inner + outer) / 2
        for y in (y0, y0 + 240):
            put(low, truss_h(190), mid, y, h)
        for y in range(y0, y0 + 240, k["truss_v"].height):
            put(low, k["truss_v"], outer, y + k["truss_v"].height / 2, h)
        put(high, k["turret"], outer, y0 + 12, h)
        put(high, k["cargo"], inner + side * 30, y0 + 120, h)
        put(high, k["dish"] if side < 0 else k["radiator"], outer + side * -40, y0 + 200, h)
    return with_shadow(low, high)


def frigate_section(length=150, radius=26):
    """A docked frigate's hull section, plated, with a bridge block and an engine bell."""
    def scene(p):
        hull = sd_capsule(p, (0, -length / 2 + radius, 0), (0, length / 2 - radius, 0), radius)
        return union((hull, HULL),
                     (sd_box(p, (0, length * 0.15, radius - 2), (9, 16, 5), 1.5), DARK),
                     (sd_box(p, (0, length * 0.15, radius + 3), (5, 6, 1.5), 0.5), WARM),
                     (sd_cylinder_y(p, (0, -length / 2, 0), radius * 0.6, 6), DARK),
                     (sd_box(p, (0, length * 0.32, radius - 4), (radius * 0.8, 3, 3), 1), ACCENT), k=2)
    return part(scene, (radius * 2 + 6, length + 8), factor=3)


def dock_frame(w, h):
    """A larger open dock frame with a frigate section in it."""
    k = kit()
    low, high = blank(w, h), blank(w, h)
    for x in (16, w - 16):
        column(low, k["truss_v"], x, 0, h)
    for y in (14, h - 14):
        put(low, truss_h(w - 20), w / 2, y)
    put(high, frigate_section(), w / 2, h / 2 + 6)
    put(high, k["turret"], 16, 30)
    put(high, k["turret"], w - 16, h - 30)
    return with_shadow(low, high)


def gantry_rails_tile(w, h):
    """The two gantry rail beds the cargo containers sit on (x = 82 and 398, period h)."""
    bay = crane_rail_bay()
    img = blank(w, h)
    for x in (82, w - 82):
        column(img, bay, x, 0, h)
    return img


def bridge_crane(w, h):
    """A bridge crane spanning the rail beds; its trolley (the beacon's place) is 60 px right."""
    span = w - 84

    def scene(p):
        q = mirror_x(p)
        return union((sd_box(q, (span / 2, 0, 0), (14, 28, 6), 1.5), HULL),
                     (sd_box(q, (span / 2, 0, 6), (8, 22, 1.5), 0.5), ACCENT),
                     (sd_box(p, (60, 0, 9), (16, 18, 5), 1.2), DARK),
                     (sd_cylinder_z(p, (60, 0, 14), 5, 1.5), HULL),
                     (sd_sphere(q, (span / 2, 24, 7), 1.8), RED))
    img = blank(w, h)
    put(img, truss_h(span, 30), w / 2, h / 2)
    img.alpha_composite(part(scene, (w, h)))
    return img


def cruiser_hull(w, h):
    """The half-built cruiser: plated stern, bare ribs and keel towards the bow, side scaffolds."""
    length, radius = h - 40, 58
    top = length / 2 - radius

    def scene(p):
        shell = sd_capsule(p, (0, -top, 0), (0, top, 0), radius)
        plated = np.maximum(shell, p[:, 1] - 20)
        slabs = np.abs((p[:, 1] % 26) - 13) - 3.5
        ribs = np.maximum(np.maximum(np.abs(shell) - 4.0, slabs), 20 - p[:, 1])
        return union((plated, HULL),
                     (ribs, DARK),
                     (sd_box(p, (0, top / 2 + 10, -radius * 0.55), (5, top / 2, 5), 1), DARK),
                     (sd_box(p, (0, -top * 0.4, radius - 3), (12, 30, 6), 1.5), DARK),
                     (sd_cylinder_y(mirror_x(p), (22, -top - radius, -6), 14, 10), ACCENT),
                     (sd_box(p, (0, 10, radius - 2), (radius * 0.7, 3, 2.5), 0.8), WARM))
    hull = part(scene, (radius * 2 + 8, h), factor=3, colors=48)
    k = kit()
    low = blank(w, h)
    for x in (18, w - 18):
        column(low, k["truss_v"], x, 10, h - 10)
    for y in (70, 230, 390):
        put(low, truss_h(w - 30, 20), w / 2, y)
    high = blank(w, h)
    put(high, hull, w / 2, h / 2)
    return with_shadow(low, high)


def perimeter_tile(w, h):
    """The yard's perimeter: a heavy truss on the left with arrays and sensors off it (period h)."""
    k = kit()
    low, high = blank(w, h), blank(w, h)
    for x in (48, 92):
        for y in range(0, h, k["truss_v"].height):
            put(low, k["truss_v"], x, y + k["truss_v"].height / 2, h)
    for y in range(19, h, 76):
        put(low, truss_h(44, 18), 70, y, h)
    put(low, k["solar_r"], 92, 140, h)
    put(low, k["radiator"], 150, 420, h)
    put(high, k["dish"], 48, 300, h)
    put(high, k["drum_s"], 92, 520, h)
    column(low, k["truss_v"], w - 30, 0, h)
    return with_shadow(low, high)


def platform_model(damaged):
    """A CDF defence platform: deck ring, gun dome, sensor mast, two short array wings."""
    def scene(p):
        q = mirror_x(p)
        d, m = union((sd_cylinder_z(p, (0, 0, 0), 40, 4), HULL),
                     (sd_cylinder_z(p, (0, 0, 4), 30, 1.5), DARK),
                     (sd_sphere(p, (0, 0, 2), 18), HULL),
                     (sd_capsule(p, (-4, 6, 12), (-4, 30, 12), 2.4), DARK),
                     (sd_capsule(p, (4, 6, 12), (4, 30, 12), 2.4), DARK),
                     (sd_box(q, (54, 0, 0), (16, 20, 1), 0.3), SOLAR),
                     (sd_sphere(q, (40, 0, 4), 2.5), RED), k=1.5)
        if damaged:   # blown-out deck sections and a broken wing
            for c, r in (((-22, -18, 4), 12), ((20, 20, 4), 10), ((58, -8, 0), 14)):
                d = np.maximum(d, -sd_sphere(p, c, r))
        return d, m
    return scene


def platform(w, h):
    return part(platform_model(False), (w, h), factor=4, colors=40)


def platform_burning(w, h, n):
    """The damaged platform with flames and smoke at its breaches; n frames of a calm flicker."""
    base = part(platform_model(True), (w, h), factor=4, colors=40)
    a = np.array(base).astype(np.float64)
    a[..., :3] *= 0.72                                       # scorched
    base = Image.fromarray(a.astype(np.uint8), "RGBA")
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    breaches = ((w / 2 - 22, h / 2 + 18), (w / 2 + 20, h / 2 - 20), (w / 2 + 50, h / 2 + 8))
    frames = []
    for f in range(n):
        arr = np.array(base).astype(np.float64) / np.array([1, 1, 1, 255])
        flicker = raster.value_noise(w, h, 6, 100 + f, period=False)
        for i, (bx, by) in enumerate(breaches):
            r = np.hypot(xx - bx, (yy - by) * 1.2) / (14 + 2 * np.sin(f * np.pi / 2 + i))
            smoke = np.exp(-np.hypot(xx - bx - 10 - f, yy - by - 12 - f) ** 2 / 300) * 0.4
            over(arr, np.array([60, 60, 72], float), smoke)
            heat = np.clip(1 - r, 0, 1) * (0.7 + 0.6 * flicker)
            over(arr, np.array([180, 84, 40], float), np.clip(heat * 1.8, 0, 1))
            over(arr, np.array([230, 190, 130], float), np.clip(heat * 2 - 1, 0, 1))
        frames.append(posterize(rgba(arr[..., :3], arr[..., 3] * 255), 40))
    return frames


# --------------------------------------------------------------------------- low-air and high-air

def lattice_beam(w, h):
    img = blank(w, h)
    put(img, truss_h(w, 30), w / 2, h / 2)
    return img


def crane_jib(w, h):
    """A tower crane's jib: a truss arm with a counterweight at the left and the hook at the right."""
    def scene(p):
        return union((sd_box(p, (-w / 2 + 24, 0, 2), (20, 18, 6), 1.5), DARK),
                     (sd_box(p, (-w / 2 + 24, 0, 8), (14, 12, 1), 0.5), ACCENT),
                     (sd_box(p, (w / 2 - 22, 0, 2), (6, 8, 3), 0.8), HULL),
                     (sd_sphere(p, (w / 2 - 10, 0, 4), 2), RED))
    img = blank(w, h)
    put(img, truss_h(w - 40, 26), w / 2 + 10, h / 2)
    img.alpha_composite(part(scene, (w, h)))
    return img


def banks(w, h, cover_share):
    """Cloud decks covering about ``cover_share`` of the screen (atmosphere intensity), tiling
    in x and y so they can drift; r03's billowy shading, posterized, stepped alpha."""
    n = r03.noise(w, h, [160, 80, 40, 20], 301, gains=[1.0, 0.5, 0.3, 0.15])
    soft = 0.12
    cover = np.quantile(n, 1 - cover_share) - soft / 2
    tones = [tuple(int(c * k + g) for c in SEA[i]) for i, k, g in
             ((1, 0.8, 30), (2, 0.5, 70), (4, 0.5, 100), (5, 0.6, 80))]
    arr = wrap_padded(lambda big: r03.bank(big, cover, soft, tones, max_alpha=235), n)
    img = r03.step_alpha(posterize(Image.fromarray(arr, "RGBA"), 12))
    return r03.OrbitScene._dim(img, 0.85)


def wisps(w, h):
    """Thin wisps for the additive high-air layer (drawn at 40 % opacity)."""
    n = r03.noise(w, h, [96, 48, 24, 12], 311)
    a = np.clip((n - 0.7) * 3.4, 0, 1) ** 1.3 * 150
    return r03.step_alpha(rgba(np.broadcast_to(np.array(SEA[5], float) * 0.9, a.shape + (3,)), a), 10)


def spark_streaks(w, h):
    """Thin spark streaks from the burning platforms, for the additive high-air layer."""
    arr = np.zeros((h, w, 4))
    rng = np.random.default_rng(51)
    for _ in range(46):
        x, y, length = int(rng.uniform(0, w)), int(rng.uniform(0, h)), int(rng.uniform(6, 20))
        for i in range(length):
            arr[(y - i) % h, x] = (235, 205, 150, (1 - i / length) * rng.uniform(0.5, 1.0))
    return rgba(arr[..., :3], arr[..., 3] * 255)


TILE_SETS = {
    "earth": earth_tile, "dock-frames": dock_frames_tile,
    "gantry-rails": gantry_rails_tile, "perimeter": perimeter_tile,
    "banks-light": lambda w, h: banks(w, h, 0.12), "banks-medium": lambda w, h: banks(w, h, 0.22),
    "wisps": wisps, "spark-streaks": spark_streaks,
}
PIECES = {
    "earth-dawn": earth_dawn, "moon": moon, "earth-limb": earth_limb, "vrell-glow": vrell_glow,
    "north-arm": north_arm, "stormhawk-far": stormhawk_far, "launch-rail": launch_rail,
    "crossbeam": crossbeam, "dock-frame": dock_frame, "bridge-crane": bridge_crane,
    "cruiser-hull": cruiser_hull, "platform-burning": platform_burning, "platform": platform,
    "lattice-beam": lattice_beam, "crane-jib": crane_jib,
}


def save(img, name, size):
    if img.size != size:
        raise ValueError(f"{name}: rendered {img.size}, the data file says {size}")
    info = PngInfo()
    info.add_text("Placeholder", NOTE)
    img.save(OUT / f"{name}.png", pnginfo=info, optimize=True)


def main():
    backdrop = yaml.safe_load(LEVEL.read_text(encoding="utf-8"))["backdrop"]
    wanted = set(sys.argv[1:])
    unknown = wanted - TILE_SETS.keys() - PIECES.keys()
    if unknown or backdrop["tile_sets"].keys() - TILE_SETS.keys() or backdrop["pieces"].keys() - PIECES.keys():
        raise SystemExit(f"no generator for {sorted(unknown) or 'a tile set or piece of the data file'}")
    OUT.mkdir(parents=True, exist_ok=True)
    width = 480
    for name, spec in backdrop["tile_sets"].items():
        if not wanted or name in wanted:
            save(TILE_SETS[name](width, spec["height"]), name, (width, spec["height"]))
            print("tile set", name)
    for name, spec in backdrop["pieces"].items():
        if wanted and name not in wanted:
            continue
        w, h = spec["size"]
        count = spec.get("frames") or spec.get("headings")
        if count:
            for i, img in enumerate(PIECES[name](w, h, count)):
                save(img, f"{name}_{i}", (w, h))
        else:
            save(PIECES[name](w, h), name, (w, h))
        print("piece", name)


if __name__ == "__main__":
    main()
