#!/usr/bin/env python3
"""Ground-target placeholders: the loot targets of Level 01, drawn to the art direction's loot-target
readability rule (design/art-direction, readability rule 7).

Outputs (assets/sprites/, Git LFS), sizes from the `ground_targets` of
design/campaign/act-1-first-contact/level-01-break-at-dawn/data.yaml:
  cargo-container_0.png        intact: rust body, amber/black hazard bands, corrugated roof, 1 px light rim
  cargo-container_1.png        damaged (after the first hit): scorch marks, a hole, a cracked rim
  cargo-container-break_N.png  8 frames, 48x48: the damaged container breaking apart (normal blend)
  beacon_0..3.png              the crane beacon: 0 dark, 1 lit; 2 and 3 the same after the first hit
  glint_0..2.png               9x9 sparkle drawn additively on a loot target about every 2 s

Pre-rendered with the concept kit (render/sdf.py, key light top-left, palette B) like the station
parts; every PNG carries a "Placeholder" text chunk naming this script. The game picks the frames
from the simulation state (hits taken, tick): see vanguard.game.render.LevelRenderer.

Run: python3 tools/concept/ground_targets.py   (a few seconds)
"""
import sys
from pathlib import Path

import numpy as np
import yaml
from PIL import Image
from PIL.PngImagePlugin import PngInfo

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render import sdf, sprite  # noqa: E402
from render.config import ROOT  # noqa: E402
from render.palette import B  # noqa: E402
from render.sdf import Material, mirror_x, sd_box, sd_cylinder_z, sd_sphere, union  # noqa: E402

LEVEL = ROOT / "design" / "campaign" / "act-1-first-contact" / "level-01-break-at-dawn" / "data.yaml"
OUT = ROOT / "assets" / "sprites"
NOTE = ("Placeholder for Level 01's loot targets, generated by tools/concept/ground_targets.py "
        "(art direction, readability rule 7); not final art.")
RIM = np.array([255, 236, 190], float)          # the 1 px light rim, warm white
SCORCH = np.array([24, 16, 14], float)
BODY, HAZARD, STEEL, LENS = range(4)
BREAK_SIZE, BREAK_FRAMES = 48, 8


def hazard_stripes(p, n):
    """Diagonal black stripes, 3 px wide every 6 px, over the amber."""
    return np.where(((p[:, 0] + p[:, 1]) / 6) % 1 < 0.5, 0.16, 1.0)


def materials(lit):
    lens = (Material((0.25, 0.04, 0.04), emission=(2.2, 0.3, 0.22)) if lit
            else Material((0.3, 0.06, 0.06), shininess=80, spec=0.8))
    return [Material((0.55, 0.24, 0.1), metal=0.2, shininess=30, spec=0.3),
            Material((0.98, 0.66, 0.14), metal=0.0, shininess=8, spec=0.05, pattern=hazard_stripes),
            Material(B.f("UTC HULL", 1), metal=0.6, shininess=40, spec=0.5),
            lens]


def render(scene, size, mats, factor=4, colors=32):
    w, h = size
    hi = sdf.render(scene, mats, (w * factor, h * factor), float(w), z_top=max(w, h), steps=150)
    return np.array(sprite.make_sprite(hi, factor, colors, crisp=60)).astype(np.float64)


def light_rim(arr):
    """Lighten the silhouette's outermost pixels: full on the lit top-left, 70 % bottom-right."""
    solid = arr[..., 3] > 0
    inner = solid.copy()
    inner[1:, :] &= solid[:-1, :]
    inner[:-1, :] &= solid[1:, :]
    inner[:, 1:] &= solid[:, :-1]
    inner[:, :-1] &= solid[:, 1:]
    edge = solid & ~inner
    h, w = solid.shape
    yy, xx = np.mgrid[0:h, 0:w]
    k = np.where((xx < w / 2) | (yy < h / 2), 0.85, 0.6)[..., None]
    arr[..., :3] = np.where(edge[..., None], arr[..., :3] * (1 - k) + RIM * k, arr[..., :3])
    return arr


def scorch(arr, spots, seed):
    """Darken soft-edged scorch spots [(x, y, r)] with a speckled edge."""
    h, w = arr.shape[:2]
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    speckle = np.random.default_rng(seed).random((h, w))
    for x, y, r in spots:
        burn = np.clip(1.3 - np.hypot(xx - x, yy - y) / r, 0, 1) * (0.6 + 0.4 * speckle)
        arr[..., :3] = arr[..., :3] * (1 - burn[..., None]) + SCORCH * burn[..., None]
    return arr


def cargo_container(w, h):
    hw, hh = w / 2 - 0.5, h / 2 - 0.5
    band = 4.0

    def scene(p):
        q = mirror_x(p)
        parts = [(sd_box(p, (0, 0, 0), (hw - 0.4, hh - 0.4, 6), 1.0), BODY),
                 (sd_box(q, (hw - band, 0, 0.3), (band, hh, 6.3), 0.8), HAZARD)]
        parts += [(sd_box(p, (x, 0, 6.2), (0.7, hh - 2, 0.6), 0.3), BODY) for x in range(-8, 9, 4)]
        return union(*parts)
    intact = light_rim(render(scene, (w, h), materials(False)))
    damaged = scorch(intact.copy(), [(w * 0.64, h * 0.38, 7), (w * 0.3, h * 0.66, 5)], 7)
    hx, hy = int(w * 0.64), int(h * 0.38)
    damaged[hy - 1:hy + 2, hx - 2:hx + 2, :3] = SCORCH * 0.6               # the hole
    for i in range(6):                                                     # a crack to the rim
        damaged[max(hy - 2 - i, 0), hx + 2 + i // 2, :3] = SCORCH
    return intact, damaged


def break_apart(damaged, size=BREAK_SIZE, frames=BREAK_FRAMES, seed=5):
    """The damaged container cut into six pieces flying apart, turning and charring, then fading."""
    h, w = damaged.shape[:2]
    img = Image.fromarray(damaged.astype(np.uint8), "RGBA")
    rng = np.random.default_rng(seed)
    cells = [(cx, cy) for cy in range(2) for cx in range(3)]
    cw, ch = w // 3, h // 2
    pieces = []
    for cx, cy in cells:
        box = (cx * cw, cy * ch, w if cx == 2 else (cx + 1) * cw, h if cy == 1 else (cy + 1) * ch)
        centre = np.array([(box[0] + box[2]) / 2 - w / 2, (box[1] + box[3]) / 2 - h / 2])
        direction = centre / max(np.hypot(*centre), 1) + rng.uniform(-0.25, 0.25, 2)
        pieces.append((img.crop(box), centre, direction * rng.uniform(2.0, 2.6), rng.uniform(-14, 14)))
    out = []
    for f in range(frames):
        frame = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        for piece, centre, velocity, spin in pieces:
            p = piece.rotate(spin * f, resample=Image.NEAREST, expand=True)
            a = np.array(p).astype(np.float64)
            a[..., :3] *= 1 - 0.07 * f                                      # charring
            a[..., 3] *= 1 if f < frames - 3 else (frames - f) / 4          # fade out, stepped
            p = Image.fromarray(a.astype(np.uint8), "RGBA")
            x, y = centre + velocity * (f + 1) + size / 2
            frame.alpha_composite(p, (int(round(x - p.width / 2)), int(round(y - p.height / 2))))
        out.append(frame)
    return out


def beacon(w, h):
    """The crane beacon from above: an amber-striped housing with a red lens; dark, lit, damaged."""
    r = w / 2 - 0.5

    def scene(p):
        return union((sd_cylinder_z(p, (0, 0, 0), r - 0.3, 2.0), HAZARD),
                     (sd_cylinder_z(p, (0, 0, 2.0), r - 2.6, 0.8), STEEL),
                     (sd_sphere(p, (0, 0, 2.2), r * 0.5), LENS))
    frames = [light_rim(render(scene, (w, h), materials(lit), factor=6, colors=24)) for lit in (False, True)]
    for f in frames[:2]:
        damaged = scorch(f.copy(), [(w * 0.75, h * 0.7, 3)], 3)
        for i in range(-2, 3):                                             # cracked lens
            damaged[h // 2 + i, w // 2 - i // 2, :3] = SCORCH
        frames.append(damaged)
    return frames


def glints(size=9):
    """A four-point sparkle growing and shrinking: arms 1, 4 and 2 px (additive, alpha = strength)."""
    c = size // 2
    out = []
    for arm in (1, 4, 2):
        a = np.zeros((size, size, 4))
        a[..., :3] = (255, 244, 214)
        for i in range(-arm, arm + 1):
            fall = 1 - abs(i) / (arm + 1)
            a[c, c + i, 3] = max(a[c, c + i, 3], fall)
            a[c + i, c, 3] = max(a[c + i, c, 3], fall)
        if arm > 2:
            for d in (-1, 1):
                a[c + d, c + d, 3] = a[c + d, c - d, 3] = 0.5
        a[..., 3] *= 255
        out.append(Image.fromarray(a.astype(np.uint8), "RGBA"))
    return out


def save(img, name):
    if isinstance(img, np.ndarray):
        img = Image.fromarray(np.clip(img, 0, 255).astype(np.uint8), "RGBA")
    info = PngInfo()
    info.add_text("Placeholder", NOTE)
    img.save(OUT / f"{name}.png", pnginfo=info, optimize=True)


def main():
    targets = {t["target"]: t for t in yaml.safe_load(LEVEL.read_text(encoding="utf-8"))["ground_targets"]}
    OUT.mkdir(parents=True, exist_ok=True)
    intact, damaged = cargo_container(*targets["cargo container"]["size"])
    save(intact, "cargo-container_0")
    save(damaged, "cargo-container_1")
    for i, frame in enumerate(break_apart(damaged)):
        save(frame, f"cargo-container-break_{i}")
    for i, frame in enumerate(beacon(*targets["beacon"]["size"])):
        save(frame, f"beacon_{i}")
    for i, frame in enumerate(glints()):
        save(frame, f"glint_{i}")


if __name__ == "__main__":
    main()
