#!/usr/bin/env python3
"""UI kit placeholders for the game: the bitmap fonts and the title scene of the out-of-game screens.

Outputs (assets/, PNGs in Git LFS):
  assets/fonts/label-8x12.fnt + .png      label font, 8x12 cells
  assets/fonts/body-10x20.fnt + .png      body font, 10x20 cells
  assets/fonts/heading-20x30.fnt + .png   heading font, 20x30 cells
  assets/ui/title-scene.png               the hero scene of main menu A (960x540), without logo and menu
  assets/ui/title-logo.png                logo D on a transparent canvas, 460 px wide as on main menu A
  assets/ui/<act>-title.png               an act title card's chrome lettering (the act number above the
                                          act's name) on a transparent canvas, per act data file

The fonts are the chosen UI kit's production fonts (ui-kit-r08-a): DejaVu Sans Mono Bold rasterised
1-bit into fixed cells by ui_r08.bitmap_glyphs, the same character set. Each glyph is stored
cropped to its pixels in a BMFont text file (white, tinted at run time) with the cell width as
advance, so every font stays monospaced. The scene and the logo are the chosen main menu A's
(ui_r06.hero_backdrop, ui_r06.logo_layer), rendered without the menu panel and logo that the
concept sheet has baked in. The act titles use the chosen act title card's chrome treatment
(ui_r08.chrome_title, act-title-r08-a) with the act number and name of design/campaign/<act>/data.yaml;
the game draws the scene, the rules and the smaller lines itself. Every PNG carries a "Placeholder"
text chunk naming this script.

Run: python3 tools/concept/ui_assets.py [fonts] [scene] [acts]   (all by default; the scene takes ~1 min)
"""
import sys
from pathlib import Path

import numpy as np
import yaml
from PIL import Image
from PIL.PngImagePlugin import PngInfo

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ui_r06  # noqa: E402
import ui_r08  # noqa: E402
from render.config import ROOT  # noqa: E402

FONTS = ROOT / "assets" / "fonts"
UI = ROOT / "assets" / "ui"
# (file name, cell width, cell height, point size): ui_r08.FONT_SPECS
SPECS = [("label-8x12", 8, 12, 9), ("body-10x20", 10, 20, 15), ("heading-20x30", 20, 30, 26)]
PAGE_WIDTH = 256
# The act name's top below the act number's top on act-title-r08-a (214 - 138).
ACT_NAME_Y = 76
NOTE = "Placeholder generated by tools/concept/ui_assets.py from the chosen UI kit (ui-kit-r08-a) and main menu A"


def save(img, path):
    info = PngInfo()
    info.add_text("Placeholder", NOTE)
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, pnginfo=info)
    print("wrote", path.relative_to(ROOT))


def baseline(cell_h, size):
    """The baseline's row in the cell, as bitmap_glyphs places the font's ascent."""
    from PIL import ImageFont
    asc, desc = ImageFont.truetype(ui_r08.FONT_PATH, size).getmetrics()
    return (cell_h - (asc + desc)) // 2 + asc


def font(name, cell_w, cell_h, size):
    glyphs = ui_r08.bitmap_glyphs(cell_w, cell_h, size)
    chars = [ch for row in ui_r08.CHARSET for ch in row]
    # Pack the cropped glyphs in rows on one page, 1 px apart.
    placed = []
    x = y = 1
    for ch in chars:
        mask = np.array(glyphs[ch]) > 0
        if not mask.any():
            placed.append((ch, None, 0, 0, 0, 0))
            continue
        rows, cols = np.where(mask)
        top, bottom, left, right = rows.min(), rows.max() + 1, cols.min(), cols.max() + 1
        w, h = right - left, bottom - top
        if x + w + 1 > PAGE_WIDTH:
            x, y = 1, y + cell_h + 1
        placed.append((ch, (left, top, right, bottom), x, y, w, h))
        x += w + 1
    height = 1
    while height < y + cell_h + 1:
        height *= 2
    page = Image.new("RGBA", (PAGE_WIDTH, height), (255, 255, 255, 0))
    lines = [
        f'info face="{name}" size={cell_h} bold=1 italic=0 charset="" unicode=1 stretchH=100 smooth=0 aa=1 '
        f"padding=0,0,0,0 spacing=1,1",
        f"common lineHeight={cell_h} base={baseline(cell_h, size)} scaleW={PAGE_WIDTH} scaleH={height} pages=1 "
        f"packed=0",
        f'page id=0 file="{name}.png"',
        f"chars count={len(placed)}",
    ]
    for ch, box, px, py, w, h in placed:
        if box is not None:
            alpha = glyphs[ch].crop(box).point(lambda v: 255 if v else 0)
            white = Image.new("RGBA", alpha.size, (255, 255, 255, 0))
            white.putalpha(alpha)
            page.alpha_composite(white, (px, py))
            xoffset, yoffset = box[0], box[1]
        else:
            px = py = xoffset = yoffset = 0
        lines.append(f"char id={ord(ch)} x={px} y={py} width={w} height={h} xoffset={xoffset} "
                     f"yoffset={yoffset} xadvance={cell_w} page=0 chnl=15")
    FONTS.mkdir(parents=True, exist_ok=True)
    fnt = FONTS / f"{name}.fnt"
    fnt.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", fnt.relative_to(ROOT))
    save(page, FONTS / f"{name}.png")


def scene():
    save(ui_r06.hero_backdrop().convert("RGB"), UI / "title-scene.png")
    save(ui_r06.logo_layer(460), UI / "title-logo.png")


def act_titles():
    """The chrome act number and name of each act's title card, stacked and centred as on the concept."""
    for data in sorted((ROOT / "design" / "campaign").glob("act-*/data.yaml")):
        card = yaml.safe_load(data.read_text(encoding="utf-8"))["title_card"]
        act = ui_r08.chrome_title(card["act"], 70, tracking=30, depth=6, width=230 * len(card["act"]) // 6)
        name = ui_r08.chrome_title(card["name"], 150, tracking=16, depth=14)
        if name.width > 760:
            name = name.resize((760, int(name.height * 760 / name.width)), Image.LANCZOS)
        width = max(act.width, name.width)
        img = Image.new("RGBA", (width, ACT_NAME_Y + name.height), (0, 0, 0, 0))
        img.alpha_composite(act, ((width - act.width) // 2, 0))
        img.alpha_composite(name, ((width - name.width) // 2, ACT_NAME_Y))
        save(img, UI / f"{data.parent.name}-title.png")


def main(args):
    targets = args or ["fonts", "scene", "acts"]
    if "fonts" in targets:
        for spec in SPECS:
            font(*spec)
    if "scene" in targets:
        scene()
    if "acts" in targets:
        act_titles()


if __name__ == "__main__":
    main(sys.argv[1:])
