#!/usr/bin/env python3
"""UI placeholders for the game: the act title cards' lettering.

Outputs (assets/, PNGs in Git LFS):
  assets/ui/<act>-title.png               an act title card's chrome lettering (the act number above the
                                          act's name) on a transparent canvas, per act data file

The act titles use the chosen act title card's chrome treatment
(ui_r08.chrome_title, act-title-r08-a) with the act number and name of design/campaign/<act>/data.yaml;
the game draws the scene, the rules and the smaller lines itself. Every PNG carries a "Placeholder"
text chunk naming this script. The title scene and logo (tools/art/ui_scenes.py) and the bitmap fonts
(tools/art/fonts.py) are production art now.

Run: python3 tools/concept/ui_assets.py
"""
import sys
from pathlib import Path

import yaml
from PIL import Image
from PIL.PngImagePlugin import PngInfo

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ui_r08  # noqa: E402
from render.config import ROOT  # noqa: E402

UI = ROOT / "assets" / "ui"
# The act name's top below the act number's top on act-title-r08-a (214 - 138).
ACT_NAME_Y = 76
NOTE = "Placeholder generated by tools/concept/ui_assets.py from the chosen UI kit (ui-kit-r08-a) and main menu A"


def save(img, path):
    info = PngInfo()
    info.add_text("Placeholder", NOTE)
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, pnginfo=info)
    print("wrote", path.relative_to(ROOT))


def act_titles():
    """The chrome act number and name of each act's title card, stacked and centred as on the concept."""
    for data in sorted((ROOT / "design" / "campaign").glob("act-*/data.yaml")):
        card = yaml.safe_load(data.read_text(encoding="utf-8"))["title_card"]
        act = ui_r08.chrome_title(card["act"], 70, tracking=30, depth=6, width=230 * len(card["act"]) // 6)
        name = ui_r08.chrome_title(card["name"], 150, tracking=16, depth=14)
        if name.width > 760:
            name = name.resize((760, int(name.height * 760 / name.width)), Image.LANCZOS)
        width = max(act.width, name.width)
        img = Image.new("RGBA", (width, ACT_NAME_Y + name.height), (0, 0, 0, 0))
        img.alpha_composite(act, ((width - act.width) // 2, 0))
        img.alpha_composite(name, ((width - name.width) // 2, ACT_NAME_Y))
        save(img, UI / f"{data.parent.name}-title.png")


def main():
    act_titles()


if __name__ == "__main__":
    main()
